name: ngp
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pytorch=1.10
  - torchvision
  - cudatoolkit=11.3
  - pytorch-lightning
  - matplotlib
  - click
  - numpy
  - scipy
  - scikit-image
  - tensorboard=2.8
  - pip
  - pip:
      - einops
      - trimesh
      - pyntcloud
      - mesh-to-sdf
      - minexr
